### ISSUE TITLE
Different Magnifying Glass Handle Direction in Location Bar

### ISSUE THREAD

**Issue by designakt** [FirefoxUX/photon-library#13]
<img width="252" alt="screen shot 2018-02-22 at 11 38 41" src="https://user-images.githubusercontent.com/8145891/36534128-f2ac103e-17c5-11e8-8736-d979f4c6f4cc.png">
In the sketch library, I noticed the magnifying glass in the location bar has the handle point in the opposite direction to what I currently see on Windows, and opposite to what it looks like on New Tab below.
(Also, the color seams a bit too dark)

**Comment by aminalhazwani** [comment]
<img width="583" alt="screen shot 2018-06-14 at 4 31 40 pm" src="https://user-images.githubusercontent.com/1721875/41443283-c1eea636-6ff0-11e8-99ba-2f86306d98e6.png">

Direction is now correct. Colors still need to be fixed, both the icon fill and text field placeholder. My suggestion would be to set the text to Grey 50 `#737373` instead of the current `#808080`. For the icon the current fill color is Grey 90 a60 which we use for secondary icons but this icon is not actionable so maybe we could set those type of icons - let's call them placeholder icons - to Grey 90 a40?
